services:
  planin-be:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - dokploy-network
    environment:
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - RUN_SEEDS=${RUN_SEEDS:-false}
      - DOKU_IS_PRODUCTION=${DOKU_IS_PRODUCTION}
      - DOKU_CLIENT_ID=${DOKU_CLIENT_ID}                                                                                                      
      - DOKU_CLIENT_SECRET=${DOKU_CLIENT_SECRET}              
      - SESSION_SECRET=${SESSION_SECRET}
      - SWAGGER_USERNAME=${SWAGGER_USERNAME}                                                                                                  
      - SWAGGER_PASSWORD=${SWAGGER_PASSWORD}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY} 
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL}
      - OTP_SECRET=${OTP_SECRET}
